name: Github Actions Artifact Practice

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3

      - name: Create a directory
        run: mkdir downloads
      
      - name: Add artifact
        run: |
            cd downloads
            echo "This is a file." > hello.txt
            cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: downloads

      - name: List files recursively
        run: |
          echo "Listing all files recursively:"
          ls -R downloads

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v3
        
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: files
          path: artifact
          
      - name: Display structure of download files
        run: ls -R artifact






