name: Run main.py

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2


      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run main.py
        run: python main.py
        
      - name: Run stage1.py
        run: python stage1.py
        
      - name: Run stage2.py
        run: python stage2.py
